### PR TITLE
Python module namespacing

### PR DESCRIPTION
**Pull request by jhesketh**
The python module we are trying to create is `bubbles`, which previously
existed at the root of the project and a sub-module of `backend`.

This commit moves the package into the correct namespace, which assists
with testing by ensuring the module is installed rather than just in
the system path.

We also keep tests out of the source directory to allow them to import
the installed module.

See: https://blog.ionelmc.ro/2014/05/25/python-packaging

### CODE REVIEW

**Comment by jhesketh** [comment]
At the moment this works because pytest is not importing bubbles, which in turn would import BubblesModule (and fail because I've removed the mock). Ideally bubbles's `__init__.py` should not need to make this import, but digging into ceph shows that it is necessary: https://tracker.ceph.com/issues/52757.

If we can remove this requirement from ceph, it will make unit testing for components that don't need MgrModule much more straight forward. Otherwise we will be stuck with a global mock, or having to do something complicated to detect when we are in unit tests (neither approach is ideal to me).

**Comment by jecluis** [comment]
out of curiosity, did you run this as part of the ceph-mgr? Because I'm pretty sure the mgr won't be able to find a "bubbles" module. "bubbles" is the namespace of the root of this repository.

**Comment by jhesketh** [comment]
Whoops, I meant to add a note that this is untested. Unfortunately I couldn't get bubbles to build for me yet and need to revisit that.

However, this should copy bubbles.py, module.py, and __init__.py as they are now in the new `bubbles` directory into `deploy/dist` (see line 49 of build-container.sh), and because of line 125 (`cp -R dist/ ${mnt}/usr/share/ceph/mgr/bubbles`) they should be available in the correct namespace for ceph-mgr.

But yes, this is unverified.

**Comment by jecluis** [comment]
@jhesketh alright, let me know when this has been verified to work and ready for a review.

**Pull request closed without merging**
